import type {
  InFictionWorld,
  WorldCodex,
  WorldDocument,
  WorldEntry,
  WorldEntryStatus,
  WorldRelationship,
  WorldSectionConfig,
  WorldWorkspace,
} from '../types';
import { worldSections } from './seedCodex';
import { CURRENT_WORLD_SCHEMA_VERSION } from './worldDocument';

export type LargeWorldFixtureOptions = {
  entriesPerSection?: number;
  relationshipCount?: number;
  planetaryWorldCount?: number;
};

const statusCycle: readonly WorldEntryStatus[] = [
  'draft',
  'canon',
  'needs-review',
  'deprecated',
];

function isoForIndex(index: number): string {
  return new Date(Date.UTC(2026, 0, 1, 12, index % 60, 0)).toISOString();
}

function createEntry(
  section: WorldSectionConfig,
  sectionIndex: number,
  entryIndex: number
): WorldEntry {
  const createdAt = isoForIndex(entryIndex);
  const name = `${section.singularTitle} ${entryIndex + 1}`;
  return {
    id: `${section.id}-${entryIndex + 1}`,
    kind: section.kind,
    name,
    summary: `${name} summary with route, faction, map, and archive terms.`,
    notes: `${name} notes include recurring performance fixture text and worldbuilding detail.`,
    tags: [
      `tag-${entryIndex % 12}`,
      `section-${sectionIndex}`,
      entryIndex % 5 === 0 ? 'shared' : 'specific',
    ],
    status: statusCycle[entryIndex % statusCycle.length],
    pinned: entryIndex % 37 === 0,
    createdAt,
    updatedAt: isoForIndex(entryIndex + sectionIndex),
    fields: Object.fromEntries(
      section.detailFields.map((field, fieldIndex) => [
        field.key,
        `${field.label} value ${entryIndex + 1}-${fieldIndex + 1}`,
      ])
    ),
  };
}

function createCodex(
  sections: readonly WorldSectionConfig[],
  entriesPerSection: number
): WorldCodex {
  return Object.fromEntries(
    sections.map((section, sectionIndex) => [
      section.id,
      Array.from({ length: entriesPerSection }, (_, entryIndex) =>
        createEntry(section, sectionIndex, entryIndex)
      ),
    ])
  ) as WorldCodex;
}

function createPlanetaryWorld(index: number): InFictionWorld {
  const timestamp = isoForIndex(index);
  return {
    id: `fixture-planet-${index + 1}`,
    name: `Fixture Planet ${index + 1}`,
    summary: 'Synthetic in-fiction world used for large-world readiness.',
    classification: index % 2 === 0 ? 'Planet' : 'Moon',
    climate: index % 2 === 0 ? 'Temperate' : 'Cold',
    dominantTerrain: index % 3 === 0 ? 'Highlands' : 'Basalt plains',
    notes: 'Generated by the deterministic large-world fixture.',
    tags: ['fixture', `orbit-${index % 4}`],
    status: statusCycle[index % statusCycle.length],
    createdAt: timestamp,
    updatedAt: timestamp,
  };
}

function createRelationships(
  entries: readonly WorldEntry[],
  relationshipCount: number
): WorldRelationship[] {
  return Array.from({ length: relationshipCount }, (_, index) => {
    const source = entries[index % entries.length];
    const target = entries[(index * 7 + 13) % entries.length];
    const timestamp = isoForIndex(index);
    return {
      id: `fixture-relationship-${index + 1}`,
      sourceEntryId: source.id,
      targetEntryId: target.id === source.id ? entries[0].id : target.id,
      type:
        index % 4 === 0
          ? 'located in'
          : index % 4 === 1
          ? 'member of'
          : index % 4 === 2
          ? 'affected by'
          : 'related to',
      directional: index % 3 !== 0,
      note: `Synthetic relationship note ${index + 1}.`,
      status: statusCycle[index % statusCycle.length],
      createdAt: timestamp,
      updatedAt: timestamp,
    };
  });
}

/**
 * Create a deterministic large world document for tests and profiling.
 */
export function createLargeWorldDocument(
  options: LargeWorldFixtureOptions = {}
): WorldDocument {
  const entriesPerSection = options.entriesPerSection ?? 500;
  const planetaryWorldCount = options.planetaryWorldCount ?? 24;
  const codex = createCodex(worldSections, entriesPerSection);
  const entries = worldSections.flatMap((section) => codex[section.id] ?? []);
  const relationshipCount = options.relationshipCount ?? entries.length * 2;
  const timestamp = isoForIndex(0);
  const workspace: WorldWorkspace = {
    id: 'large-fixture-workspace',
    name: 'Large Fixture Workspace',
    summary: 'Synthetic workspace used to measure large-world readiness.',
    defaultEra: 'Fixture Era',
    status: 'active',
    planetaryWorlds: Array.from({ length: planetaryWorldCount }, (_, index) =>
      createPlanetaryWorld(index)
    ),
    entryTypes: [...worldSections],
    codex,
    relationships: createRelationships(entries, relationshipCount),
    createdAt: timestamp,
    updatedAt: timestamp,
  };
  return {
    schemaVersion: CURRENT_WORLD_SCHEMA_VERSION,
    activeWorldId: workspace.id,
    worlds: [workspace],
    savedAt: timestamp,
  };
}
